# Generated by Django 5.2.17 on 2026-09-26 15:45

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EvaluationRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("dataset_id", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("REQUESTED", "접수 중"),
                            ("QUEUED", "실행 대기"),
                            ("RUNNING", "실행 중"),
                            ("COMPLETED", "완료"),
                            ("FAILED", "실패"),
                            ("CANCELLED", "취소"),
                            ("CRASHED", "실행 중단"),
                            ("RESULT_ERROR", "결과 확인 실패"),
                        ],
                        default="REQUESTED",
                        max_length=16,
                    ),
                ),
                ("prefect_flow_run_id", models.UUIDField(null=True, unique=True)),
                ("evaluation_run_id", models.CharField(blank=True, max_length=32)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(null=True)),
                ("finished_at", models.DateTimeField(null=True)),
                ("synced_at", models.DateTimeField(null=True)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("summary", models.JSONField(default=dict)),
                (
                    "requested_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
