# Generated by Django 5.2.17 on 2026-09-28 04:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def preserve_existing_baselines(apps, schema_editor):
    baselines = apps.get_model("evaluations", "EvaluationBaseline")
    changes = apps.get_model("evaluations", "EvaluationBaselineChange")
    alias = schema_editor.connection.alias
    for baseline in baselines.objects.using(alias).filter(review__isnull=False).iterator():
        baselines.objects.using(alias).filter(pk=baseline.pk).update(version=1)
        change = changes.objects.using(alias).create(
            baseline_id=baseline.pk,
            version=1,
            review_id=baseline.review_id,
            changed_by_id=baseline.selected_by_id,
            reason="기존 기준 이관: 이전 교체 이력과 당시 자료 해시는 확인되지 않음",
        )
        changes.objects.using(alias).filter(pk=change.pk).update(created_at=baseline.selected_at)


class Migration(migrations.Migration):
    dependencies = [
        ("evaluations", "0006_evaluationrun_sync_attempted_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="evaluationbaseline",
            name="version",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="evaluationrun",
            name="baseline_review",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="evaluations.evaluationreview",
            ),
        ),
        migrations.AddField(
            model_name="evaluationrun",
            name="baseline_version",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="evaluationbaseline",
            name="review",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="evaluations.evaluationreview",
            ),
        ),
        migrations.AlterField(
            model_name="evaluationbaseline",
            name="selected_by",
            field=models.ForeignKey(
                null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="EvaluationBaselineChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                ("reason", models.TextField()),
                ("fixture_sha256", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "baseline",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="changes",
                        to="evaluations.evaluationbaseline",
                    ),
                ),
                (
                    "changed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "previous_review",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="baseline_replacements",
                        to="evaluations.evaluationreview",
                    ),
                ),
                (
                    "review",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="baseline_selections",
                        to="evaluations.evaluationreview",
                    ),
                ),
            ],
            options={
                "ordering": ["-version"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("baseline", "version"), name="unique_baseline_version"
                    )
                ],
            },
        ),
        migrations.RunPython(preserve_existing_baselines, migrations.RunPython.noop),
    ]
