# Generated by Django 5.2.17 on 2026-09-28 05:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("evaluations", "0007_baseline_versions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="evaluationreview",
            name="fixture_sha256",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="evaluationreview",
            name="rubric_version",
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name="evaluationreview",
            name="version",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="evaluationrun",
            name="review_version",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name="EvaluationCaseReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("case_id", models.CharField(max_length=100)),
                ("version", models.PositiveIntegerField()),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("SUITABLE", "적합"),
                            ("UNSUITABLE", "부적합"),
                            ("DEFERRED", "판단 보류"),
                        ],
                        max_length=20,
                    ),
                ),
                ("comment", models.TextField()),
                ("capture_sha256", models.CharField(max_length=64)),
                ("fixture_sha256", models.CharField(max_length=64)),
                ("rubric_version", models.CharField(max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="case_reviews",
                        to="evaluations.evaluationrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-version"],
            },
        ),
        migrations.AddField(
            model_name="evaluationreview",
            name="case_reviews",
            field=models.ManyToManyField(blank=True, to="evaluations.evaluationcasereview"),
        ),
        migrations.AddConstraint(
            model_name="evaluationreview",
            constraint=models.UniqueConstraint(
                fields=("run", "version"), name="unique_run_review_version"
            ),
        ),
        migrations.AddConstraint(
            model_name="evaluationcasereview",
            constraint=models.UniqueConstraint(
                fields=("run", "version"), name="unique_case_review_version"
            ),
        ),
    ]
