# Generated by Django 5.2.17 on 2026-09-28 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("evaluations", "0009_execution_spec"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FixtureReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("dataset_id", models.CharField(max_length=100)),
                ("version", models.PositiveIntegerField()),
                ("fixture_sha256", models.CharField(max_length=64)),
                ("case_ids", models.JSONField()),
                ("rubric_version", models.CharField(max_length=40)),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("APPROVED", "검토 승인"),
                            ("CHANGES_REQUESTED", "수정 필요"),
                            ("DEFERRED", "보류"),
                        ],
                        max_length=20,
                    ),
                ),
                ("comment", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-version"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("dataset_id", "version"), name="unique_fixture_review"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="QualityAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("policy", models.JSONField()),
                ("policy_sha256", models.CharField(max_length=64)),
                ("inputs", models.JSONField()),
                ("input_sha256", models.CharField(max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PASS", "합격"),
                            ("FAIL", "불합격"),
                            ("NEEDS_REVIEW", "검토 필요"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reasons", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assessed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="assessments",
                        to="evaluations.evaluationrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("run", "input_sha256"), name="unique_quality_assessment"
                    )
                ],
            },
        ),
    ]
