# Generated by Django 5.2.17 on 2026-09-28 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("evaluations", "0010_quality_assessments"),
    ]

    operations = [
        migrations.CreateModel(
            name="EvaluationBudget",
            fields=[
                (
                    "id",
                    models.PositiveSmallIntegerField(
                        default=1, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("call_limit", models.PositiveBigIntegerField(default=0)),
                ("output_token_limit", models.PositiveBigIntegerField(default=0)),
                ("allocated_calls", models.PositiveBigIntegerField(default=0)),
                ("allocated_output_tokens", models.PositiveBigIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("id", 1)), name="single_evaluation_budget"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("allocated_calls__lte", models.F("call_limit"))),
                        name="evaluation_call_budget_limit",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("allocated_output_tokens__lte", models.F("output_token_limit"))
                        ),
                        name="evaluation_output_budget_limit",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="EvaluationBudgetReservation",
            fields=[
                (
                    "run",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        primary_key=True,
                        related_name="budget_reservation",
                        serialize=False,
                        to="evaluations.evaluationrun",
                    ),
                ),
                ("max_calls", models.PositiveSmallIntegerField()),
                ("max_output_tokens", models.PositiveIntegerField()),
                ("worker_id", models.UUIDField(null=True)),
                ("closed_at", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="evaluations.evaluationbudget",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EvaluationBudgetCall",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("sequence", models.PositiveSmallIntegerField()),
                ("input_tokens", models.PositiveBigIntegerField(null=True)),
                ("output_tokens", models.PositiveBigIntegerField(null=True)),
                ("authorized_at", models.DateTimeField(auto_now_add=True)),
                ("settled_at", models.DateTimeField(null=True)),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="calls",
                        to="evaluations.evaluationbudgetreservation",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("reservation", "sequence"), name="unique_evaluation_budget_call"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("input_tokens__isnull", True),
                                ("output_tokens__isnull", True),
                                ("settled_at__isnull", True),
                            ),
                            models.Q(
                                ("input_tokens__isnull", False),
                                ("output_tokens__isnull", False),
                                ("settled_at__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="complete_evaluation_call_usage",
                    ),
                ],
            },
        ),
    ]
