# Generated by Django 5.2.17 on 2026-09-29 05:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("evaluations", "0012_evaluation_cancellation"),
    ]

    operations = [
        migrations.CreateModel(
            name="EvaluationBudgetChange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("request_id", models.UUIDField(unique=True)),
                ("actor", models.CharField(max_length=150)),
                ("source", models.CharField(default="CLI", editable=False, max_length=10)),
                ("reason", models.CharField(max_length=1000)),
                ("previous_call_limit", models.PositiveBigIntegerField(null=True)),
                ("previous_output_token_limit", models.PositiveBigIntegerField(null=True)),
                ("call_limit", models.PositiveBigIntegerField()),
                ("output_token_limit", models.PositiveBigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="evaluations.evaluationbudget",
                    ),
                ),
            ],
            options={
                "ordering": ["-id"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("source", "CLI")), name="budget_change_cli_source"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("actor", ""), _negated=True),
                            models.Q(("reason", ""), _negated=True),
                        ),
                        name="budget_change_attribution",
                    ),
                ],
            },
        ),
    ]
