# Generated by Django 5.2.17 on 2026-09-30 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("evaluations", "0015_usage_correction"),
    ]

    operations = [
        migrations.AddField(
            model_name="evaluationbudgetcall",
            name="operation_id",
            field=models.CharField(db_collation="utf8mb4_bin", max_length=128, null=True),
        ),
        migrations.AddConstraint(
            model_name="evaluationbudgetcall",
            constraint=models.UniqueConstraint(
                fields=("reservation", "operation_id"), name="unique_evaluation_budget_operation"
            ),
        ),
        migrations.AddConstraint(
            model_name="evaluationbudgetcall",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("operation_id__isnull", True),
                    models.Q(("operation_id", ""), _negated=True),
                    _connector="OR",
                ),
                name="nonempty_evaluation_budget_operation",
            ),
        ),
    ]
