# Generated by Django 5.2.17 on 2026-09-30 13:58

from django.db import migrations, models


def preserve_known_input(apps, schema_editor):
    Budget = apps.get_model("evaluations", "EvaluationBudget")
    Call = apps.get_model("evaluations", "EvaluationBudgetCall")
    Correction = apps.get_model("evaluations", "EvaluationUsageCorrection")
    alias = schema_editor.connection.alias
    for budget in Budget.objects.using(alias).all():
        known = (
            Call.objects.using(alias)
            .filter(
                reservation__budget_id=budget.pk,
                settled_at__isnull=False,
                correction__isnull=True,
            )
            .aggregate(total=models.Sum("input_tokens", default=0))["total"]
        )
        known += (
            Correction.objects.using(alias)
            .filter(
                call__reservation__budget_id=budget.pk,
            )
            .aggregate(total=models.Sum("input_tokens", default=0))["total"]
        )
        budget.allocated_input_tokens = known
        budget.save(using=alias, update_fields=["allocated_input_tokens"])
    # Legacy bounds stay NULL. Unknown calls block enabling the input limit.


class Migration(migrations.Migration):
    dependencies = [
        ("evaluations", "0016_budget_operation_identity"),
    ]

    operations = [
        migrations.AddField(
            model_name="evaluationbudget",
            name="allocated_input_tokens",
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="evaluationbudget",
            name="input_token_limit",
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="evaluationbudgetcall",
            name="counted_input_tokens",
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="evaluationbudgetchange",
            name="input_token_limit",
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="evaluationbudgetchange",
            name="previous_input_token_limit",
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="evaluationbudgetreservation",
            name="max_input_tokens",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.RunPython(preserve_known_input, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="evaluationbudget",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("input_token_limit__isnull", True),
                    ("allocated_input_tokens__lte", models.F("input_token_limit")),
                    _connector="OR",
                ),
                name="evaluation_input_budget_limit",
            ),
        ),
    ]
