# Generated by Django 5.2.17 on 2026-09-30 14:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("evaluations", "0017_input_token_budget"),
    ]

    operations = [
        migrations.AddField(
            model_name="evaluationbudgetcall",
            name="max_input_tokens",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="evaluationbudgetcall",
            name="max_output_tokens",
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="evaluationbudgetreservation",
            name="reserved_input_tokens",
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="evaluationbudgetreservation",
            name="reserved_output_tokens",
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
