# Generated by Django 5.2.17 on 2026-09-30 15:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("evaluations", "0018_operation_token_limits"),
    ]

    operations = [
        migrations.AddField(
            model_name="evaluationusagecorrection",
            name="provider_request_id",
            field=models.CharField(max_length=200, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="evaluationusagecorrection",
            name="response_id",
            field=models.CharField(max_length=185, null=True, unique=True),
        ),
        migrations.AddConstraint(
            model_name="evaluationusagecorrection",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("provider_request_id__isnull", True),
                        ("response_id__isnull", False),
                        models.Q(("response_id", ""), _negated=True),
                    ),
                    models.Q(
                        ("provider_request_id__isnull", False),
                        ("response_id__isnull", True),
                        models.Q(("provider_request_id", ""), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="usage_correction_response_identity",
            ),
        ),
    ]
