# Generated by Django 5.2.17 on 2026-10-02 10:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("evaluations", "0020_evaluation_admission"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RagCaseReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("case_id", models.CharField(max_length=100)),
                ("version", models.PositiveIntegerField()),
                (
                    "retrieval_decision",
                    models.CharField(
                        choices=[
                            ("SUITABLE", "적합"),
                            ("UNSUITABLE", "부적합"),
                            ("DEFERRED", "판단 보류"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "answer_decision",
                    models.CharField(
                        choices=[
                            ("SUITABLE", "적합"),
                            ("UNSUITABLE", "부적합"),
                            ("DEFERRED", "판단 보류"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "citation_decision",
                    models.CharField(
                        choices=[
                            ("SUITABLE", "적합"),
                            ("UNSUITABLE", "부적합"),
                            ("DEFERRED", "판단 보류"),
                        ],
                        max_length=20,
                    ),
                ),
                ("comment", models.TextField()),
                ("material_sha256", models.CharField(max_length=64)),
                ("fixture_sha256", models.CharField(max_length=64)),
                ("candidate_capture_sha256", models.CharField(max_length=64)),
                ("reference_capture_sha256", models.CharField(max_length=64)),
                ("execution_spec_sha256", models.CharField(max_length=64)),
                ("rubric_version", models.CharField(max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rag_case_reviews",
                        to="evaluations.evaluationrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-version"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("run", "version"), name="unique_rag_case_review_version"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("version__gte", 1)), name="rag_review_version_positive"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("retrieval_decision__in", ["SUITABLE", "UNSUITABLE", "DEFERRED"])
                        ),
                        name="rag_review_retrieval_decision",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("answer_decision__in", ["SUITABLE", "UNSUITABLE", "DEFERRED"])
                        ),
                        name="rag_review_answer_decision",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("citation_decision__in", ["SUITABLE", "UNSUITABLE", "DEFERRED"])
                        ),
                        name="rag_review_citation_decision",
                    ),
                ],
            },
        ),
    ]
