# Generated by Django 5.2.17 on 2026-10-02 11:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("evaluations", "0021_rag_case_reviews"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RagReferenceReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("version", models.PositiveIntegerField()),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("APPROVED", "참조 자료 승인"),
                            ("CHANGES_REQUESTED", "수정 필요"),
                            ("DEFERRED", "판단 보류"),
                            ("REVOKED", "승인 철회"),
                        ],
                        max_length=20,
                    ),
                ),
                ("comment", models.TextField()),
                ("fixture_sha256", models.CharField(max_length=64)),
                ("case_ids", models.JSONField()),
                ("rubric_version", models.CharField(max_length=40)),
                ("execution_spec_sha256", models.CharField(max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "revoked_review",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="evaluations.ragreferencereview",
                    ),
                ),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rag_reference_reviews",
                        to="evaluations.evaluationrun",
                    ),
                ),
            ],
            options={
                "ordering": ["-version"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("run", "version"), name="unique_rag_reference_version"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("version__gte", 1)),
                        name="rag_reference_version_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "decision__in",
                                ["APPROVED", "CHANGES_REQUESTED", "DEFERRED", "REVOKED"],
                            )
                        ),
                        name="rag_reference_decision",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(("decision", "REVOKED"), ("revoked_review__isnull", False)),
                            models.Q(
                                models.Q(("decision", "REVOKED"), _negated=True),
                                ("revoked_review__isnull", True),
                            ),
                            _connector="OR",
                        ),
                        name="rag_reference_revocation_target",
                    ),
                ],
            },
        ),
    ]
