# Generated by Django 5.2.17 on 2026-10-02 11:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("evaluations", "0022_rag_reference_reviews"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="evaluationbaseline",
            name="rag_assessment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="evaluations.qualityassessment",
            ),
        ),
        migrations.AddField(
            model_name="evaluationbaselinechange",
            name="previous_rag_assessment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="baseline_replacements",
                to="evaluations.qualityassessment",
            ),
        ),
        migrations.AddField(
            model_name="evaluationbaselinechange",
            name="rag_assessment",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="baseline_selections",
                to="evaluations.qualityassessment",
            ),
        ),
        migrations.AddConstraint(
            model_name="evaluationbaseline",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("review__isnull", True), ("rag_assessment__isnull", True), _connector="OR"
                ),
                name="baseline_one_review_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="evaluationbaselinechange",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("review__isnull", True), ("rag_assessment__isnull", True), _connector="OR"
                ),
                name="baseline_change_one_review_type",
            ),
        ),
        migrations.AddConstraint(
            model_name="evaluationbaselinechange",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("previous_review__isnull", True),
                    ("previous_rag_assessment__isnull", True),
                    _connector="OR",
                ),
                name="baseline_previous_one_review_type",
            ),
        ),
    ]
