import { Text } from 'react-native'
import { fireEvent, render, screen, waitFor } from '@testing-library/react-native'
import { AppEntryGate } from './AppEntryGate'
import { completeIntroduction, readIntroductionCompleted } from './introductionStorage'
import { useAuth } from './session'

const mockRequestLogin = jest.fn()
jest.mock('./loginFlow', () => ({ useLoginFlow: () => mockRequestLogin }))
jest.mock('./session', () => ({ useAuth: jest.fn() }))
jest.mock('./introductionStorage', () => ({ completeIntroduction: jest.fn(), readIntroductionCompleted: jest.fn() }))
jest.mock('./oauth', () => ({ supportsNativeOAuth: () => false }))
const mount = () => render(<AppEntryGate><Text>기존 화면</Text></AppEntryGate>)
beforeEach(() => {
  mockRequestLogin.mockClear()
  jest.mocked(useAuth).mockReturnValue({ status: 'signedOut', session: null, refreshSession: jest.fn() } as unknown as ReturnType<typeof useAuth>)
  jest.mocked(readIntroductionCompleted).mockReset().mockResolvedValue(false)
  jest.mocked(completeIntroduction).mockReset().mockResolvedValue(undefined)
})
test('first launch waits for storage and offers four manual slides before public entry', async () => {
  mount()
  await screen.findByText('맞는 지원사업을 찾아요', {}, { timeout: 4000 })
  expect(screen.queryByText('기존 화면')).toBeNull()
  fireEvent.press(screen.getByLabelText('다음'))
  expect(screen.getByText('공고 원문 문장으로 확인해요')).toBeTruthy()
  fireEvent.press(screen.getByLabelText('이전'))
  expect(screen.getByText('맞는 지원사업을 찾아요')).toBeTruthy()
  fireEvent.press(screen.getByLabelText('로그인 없이 둘러보기'))
  await screen.findByText('기존 화면')
  expect(completeIntroduction).toHaveBeenCalledTimes(1)
  expect(mockRequestLogin).not.toHaveBeenCalled()
})
test('failed introduction writes keep the user on the introduction with an explicit retry', async () => {
  jest.mocked(completeIntroduction).mockRejectedValueOnce(new Error('storage'))
  mount()
  await screen.findByText('맞는 지원사업을 찾아요')
  fireEvent.press(screen.getByLabelText('로그인 없이 둘러보기'))
  await screen.findByText('기능 소개 기록을 저장하지 못했습니다. 다시 시도해 주세요.')
  expect(screen.queryByText('기존 화면')).toBeNull()
  expect(mockRequestLogin).not.toHaveBeenCalled()
  fireEvent.press(screen.getByLabelText('로그인 없이 둘러보기'))
  await screen.findByText('기존 화면')
  expect(mockRequestLogin).not.toHaveBeenCalled()
})
test('returning guests skip introduction while unavailable sessions need an explicit public choice', async () => {
  jest.mocked(readIntroductionCompleted).mockResolvedValue(true)
  const view = mount()
  await screen.findByText('기존 화면')
  jest.mocked(useAuth).mockReturnValue({ status: 'unavailable', session: null, refreshSession: jest.fn(), restoreError: '연결 실패' } as unknown as ReturnType<typeof useAuth>)
  view.rerender(<AppEntryGate><Text>기존 화면</Text></AppEntryGate>)
  expect(screen.queryByText('기존 화면')).toBeNull()
  fireEvent.press(screen.getByLabelText('공개 공고 둘러보기'))
  expect(screen.getByText('기존 화면')).toBeTruthy()
})
test('a restored account bypasses the introduction and does not open login', async () => {
  jest.mocked(useAuth).mockReturnValue({ status: 'signedIn', session: { accessToken: 'owner' } } as ReturnType<typeof useAuth>)
  mount()
  expect(screen.getByText('기존 화면')).toBeTruthy()
  await waitFor(() => expect(completeIntroduction).toHaveBeenCalledTimes(1))
  expect(mockRequestLogin).not.toHaveBeenCalled()
})

test('signup and existing-account methods open independently without marking a cancelled introduction completed', async () => {
  mount()
  await screen.findByLabelText('회원가입하고 시작하기')
  fireEvent.press(screen.getByLabelText('회원가입하고 시작하기'))
  expect(mockRequestLogin).toHaveBeenCalledWith({ direct: true, mode: 'signup' })
  fireEvent.press(screen.getByLabelText('이미 계정이 있습니다'))
  expect(mockRequestLogin).toHaveBeenCalledWith({ methods: true })
  expect(completeIntroduction).not.toHaveBeenCalled()
  expect(screen.getByText('맞는 지원사업을 찾아요')).toBeTruthy()
})
