"""완료된 무료 Core 캡처를 내부 RAG 예산 명세로 변환한다. 예약·모델 호출은 하지 않는다."""

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / "evaluation/support-program-evidence"))
sys.path.insert(0, str(ROOT / "backend/ai-service"))

import rag_evaluate as rag  # noqa: E402
from rag_budget import digest, make_rag_spec  # noqa: E402

PLAN_NAME = "budget-plan.json"


def build_plan(directory):
    from core_rag_capture import CHUNKER, observation

    directory = Path(directory)
    paths = {
        "fixture": directory / "fixture.json",
        "capture": directory / "capture.json",
        "wire": directory / "wire.json",
        "integration": directory.parent / "integration.json",
    }
    records = {key: rag.read_json(path) for key, path in paths.items()}
    fixture, capture, wire, integration = (records[key][0] for key in paths)
    documents, cases = rag.validate_fixture(fixture)
    report = rag.evaluate(paths["fixture"], paths["capture"])
    rag.require(
        report["fixtureSha256"] == records["fixture"][1]
        and report["captureSha256"] == records["capture"][1],
        "Capture inputs changed during validation",
    )
    rag.require(
        report["measurementKind"] == "integration-stub-replay"
        and integration.get("status") == "passed"
        and type(integration.get("paid_model_api_calls")) is int
        and integration["paid_model_api_calls"] == 0
        and wire.get("status") == "passed"
        and sum(record == wire for record in integration.get("versions", [])) == 1,
        "A completed, zero-paid-call Core integration capture is required",
    )
    chunker_hash = rag.digest(CHUNKER.read_bytes())
    rag.require(
        all(d["chunkVersion"] == "core-sha256:" + chunker_hash for d in documents.values()),
        "Core chunker version differs from the captured source",
    )
    rag.require(
        [row["id"] for row in wire["cases"]] == list(cases)
        and [row["caseId"] for row in capture["cases"]] == list(cases),
        "Core wire, capture and fixture case order must match without omissions",
    )
    material, traces = [], set()
    for case, saved, observed in zip(cases.values(), wire["cases"], capture["cases"], strict=True):
        document = documents[case["documentId"]]
        rag.require(
            all(
                citation["sourceUrl"] == document["sourceUrl"]
                for citation in saved["publicResponse"].get("citations", [])
            ),
            "Core citation source URL differs from the fixture",
        )
        trace_id = saved["traceId"]
        rag.require(trace_id is not None and trace_id not in traces, "Missing or reused Core trace")
        traces.add(trace_id)
        reconstructed = observation(
            case["id"],
            trace_id,
            document["content"],
            document["chunks"],
            saved["aiCalls"],
            saved["publicStatus"],
            saved["publicResponse"],
        )
        rag.require(reconstructed == observed, "Core wire differs from the saved RAG observation")
        material.append(
            {
                "case_id": case["id"],
                "chunks": document["chunks"],
                "question": case["question"],
                "limit": rag.search_request(case, document)["limit"],
            }
        )
    execution = make_rag_spec(material)
    # A plan fixes future inputs. It does not retroactively approve or settle the captured calls.
    return {
        "schemaVersion": "core-rag-budget-plan-v1",
        "measurementKind": "integration-stub-replay",
        "baselineEligible": False,
        "reservationCreated": False,
        "paidModelApiCalls": 0,
        "sourceSha256": {key: value[1] for key, value in records.items()},
        "preparationSha256": {
            str(path.relative_to(ROOT)): rag.digest(path.read_bytes())
            for path in (
                Path(__file__).resolve(),
                Path(__file__).with_name("core_rag_capture.py"),
                Path(rag.__file__),
                CHUNKER,
            )
        },
        "executionSpecSha256": digest(execution),
        "executionSpec": execution,
    }


def prepare(directory):
    plan = build_plan(directory)
    # Refuse overwriting a reviewed plan, including a plan generated by another process.
    with (Path(directory) / PLAN_NAME).open("x", encoding="utf-8") as target:
        target.write(json.dumps(plan, ensure_ascii=False, indent=2, allow_nan=False) + "\n")
    return plan


def load_plan(directory):
    plan, _ = rag.read_json(Path(directory) / PLAN_NAME)
    rag.require(
        rag.json_digest(plan) == rag.json_digest(build_plan(directory)),
        "Budget plan is stale or modified; prepare fresh inputs",
    )
    return plan


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("action", choices=("prepare", "check"))
    parser.add_argument("directory", type=Path)
    args = parser.parse_args()
    plan = (prepare if args.action == "prepare" else load_plan)(args.directory)
    print(
        json.dumps(
            {
                "executionSpecSha256": plan["executionSpecSha256"],
                "caseCount": len(plan["executionSpec"]["rag_cases"]),
                "maxModelCalls": plan["executionSpec"]["live_config"]["max_model_calls"],
                "reservationCreated": False,
                "paidModelApiCalls": 0,
            }
        )
    )


if __name__ == "__main__":
    main()
