import { fireEvent, render, screen } from '@testing-library/react-native'
import { colors } from '../ui'
import { WelcomeScreen } from './WelcomeScreen'

test('four introduction previews show the actual condition and result card vocabulary without interactive searches', () => {
  jest.useFakeTimers().setSystemTime(new Date('2026-10-02T03:00:00Z'))
  const signup = jest.fn(); const login = jest.fn(); const browse = jest.fn()
  render(<WelcomeScreen busy={false} error={null} onSignup={signup} onLogin={login} onBrowse={browse} />)
  expect(screen.getByText('이 조건으로 검색할까요?')).toBeTruthy()
  expect(screen.queryByRole('button', { name: '이 조건으로 검색' })).toBeNull()
  fireEvent.press(screen.getByLabelText('다음'))
  expect(screen.getByText('2026 스마트공장 고도화 지원사업 2차')).toBeTruthy()
  expect(screen.getByText('청년일자리 도약장려금 하반기')).toBeTruthy()
  expect(screen.getAllByTestId('program-status-dot')).toHaveLength(2)
  expect(screen.getByText('D-5')).toBeTruthy()
  expect(screen.getByText('D-3')).toBeTruthy()
  expect(screen.getByText('조건 확인')).toHaveStyle({ backgroundColor: colors.soft })
  expect(screen.getByText('확인 필요')).toHaveStyle({ backgroundColor: colors.warningSoft })
  fireEvent.press(screen.getByLabelText('다음'))
  expect(screen.getByText('원문 근거 답변 · 예시')).toBeTruthy()
  fireEvent.press(screen.getByLabelText('다음'))
  expect(screen.getByText('사업계획서_초안_v4.hwpx')).toBeTruthy()
  fireEvent.press(screen.getByLabelText('회원가입하고 시작하기'))
  fireEvent.press(screen.getByLabelText('이미 계정이 있습니다'))
  fireEvent.press(screen.getByLabelText('로그인 없이 둘러보기'))
  expect(signup).toHaveBeenCalledTimes(1)
  expect(login).toHaveBeenCalledTimes(1)
  expect(browse).toHaveBeenCalledTimes(1)
})

afterEach(() => jest.useRealTimers())


test('horizontal swipe, progress selection and first/last limits keep existing authentication actions separate', () => {
  const browse = jest.fn(), login = jest.fn(), signup = jest.fn()
  const view = render(<WelcomeScreen busy={false} error={null} onBrowse={browse} onLogin={login} onSignup={signup} />)
  fireEvent(screen.getByTestId('welcome-carousel'), 'layout', { nativeEvent: { layout: { width: 360 } } })
  fireEvent(screen.getByTestId('welcome-carousel'), 'momentumScrollEnd', { nativeEvent: { contentOffset: { x: 360 } } })
  expect(screen.getByText('2 / 4')).toBeTruthy()
  expect(screen.getByText('공고 원문 문장으로 확인해요')).toBeTruthy()
  fireEvent.press(screen.getByLabelText('이전'))
  expect(screen.getByText('1 / 4')).toBeTruthy()
  fireEvent(screen.getByTestId('welcome-carousel'), 'momentumScrollEnd', { nativeEvent: { contentOffset: { x: -100 } } })
  expect(screen.getByText('1 / 4')).toBeTruthy()
  fireEvent.press(screen.getByLabelText('온보딩 4장 보기'))
  fireEvent(screen.getByTestId('welcome-carousel'), 'momentumScrollEnd', { nativeEvent: { contentOffset: { x: 1600 } } })
  expect(screen.getByText('4 / 4')).toBeTruthy()
  expect(browse).not.toHaveBeenCalled()
  view.rerender(<WelcomeScreen busy error={null} onBrowse={browse} onLogin={login} onSignup={signup} />)
  fireEvent(screen.getByTestId('welcome-carousel'), 'momentumScrollEnd', { nativeEvent: { contentOffset: { x: 0 } } })
  expect(screen.getByText('4 / 4')).toBeTruthy()
  expect(screen.getByTestId('welcome-carousel').props.scrollEnabled).toBe(false)
})


test('changing the viewport preserves the selected page and uses its new width for subsequent swipes', () => {
  render(<WelcomeScreen busy={false} error={null} onBrowse={jest.fn()} onLogin={jest.fn()} onSignup={jest.fn()} />)
  fireEvent(screen.getByTestId('welcome-carousel'), 'layout', { nativeEvent: { layout: { width: 320 } } })
  fireEvent.press(screen.getByLabelText('온보딩 3장 보기'))
  expect(screen.getByText('3 / 4')).toBeTruthy()
  expect(screen.getByText('궁금한 조건은')).toBeTruthy()
  expect(screen.queryByText('말로 물어보면')).toBeNull()
  fireEvent(screen.getByTestId('welcome-carousel'), 'layout', { nativeEvent: { layout: { width: 640 } } })
  expect(screen.getByText('3 / 4')).toBeTruthy()
  fireEvent(screen.getByTestId('welcome-carousel'), 'momentumScrollEnd', { nativeEvent: { contentOffset: { x: 640 } } })
  expect(screen.getByText('2 / 4')).toBeTruthy()
  expect(screen.getByText('공고 원문 문장으로 확인해요')).toBeTruthy()
  expect(screen.queryByText('궁금한 조건은')).toBeNull()
  fireEvent(screen.getByTestId('welcome-carousel'), 'layout', { nativeEvent: { layout: { width: 0 } } })
  fireEvent(screen.getByTestId('welcome-carousel'), 'momentumScrollEnd', { nativeEvent: { contentOffset: { x: 1280 } } })
  expect(screen.getByText('3 / 4')).toBeTruthy()
})

test('busy entry blocks page and account actions, then exposes the saved error and restores interaction', () => {
  const browse = jest.fn(), login = jest.fn(), signup = jest.fn()
  const view = render(<WelcomeScreen busy={false} error={null} onBrowse={browse} onLogin={login} onSignup={signup} />)
  fireEvent.press(screen.getByLabelText('온보딩 2장 보기'))
  view.rerender(<WelcomeScreen busy error={null} onBrowse={browse} onLogin={login} onSignup={signup} />)
  for (const label of ['온보딩 4장 보기', '이전', '다음', '회원가입하고 시작하기', '이미 계정이 있습니다', '로그인 없이 둘러보기']) {
    fireEvent.press(screen.getByLabelText(label))
  }
  expect(screen.getByText('2 / 4')).toBeTruthy()
  expect(browse).not.toHaveBeenCalled()
  expect(login).not.toHaveBeenCalled()
  expect(signup).not.toHaveBeenCalled()
  view.rerender(<WelcomeScreen busy={false} error="소개 기록 저장 실패" onBrowse={browse} onLogin={login} onSignup={signup} />)
  expect(screen.getByText('소개 기록 저장 실패')).toBeTruthy()
  fireEvent.press(screen.getByLabelText('온보딩 4장 보기'))
  expect(screen.getByText('4 / 4')).toBeTruthy()
  fireEvent.press(screen.getByLabelText('둘러보기'))
  expect(browse).toHaveBeenCalledTimes(1)
})
